apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkedin-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linkedin-storageclass
  resources:
    requests:
      storage: 1Gi